Lab grade computation
---------------------

..	cssclass::	table-bordered
..	cssclass::	table-striped
..  csv-table::
    :widths: 30,15

    "Compile with no errors","15 percent"
    "Run with no errors","15 percent"
    "Produce correct output","20 percent"
    "Algorithm design","20 percent"
    "Follow recommended style guidelines","15 percent"
    "Includes documentation","15 percent"


Each homework or lab project is due one week following the class in
which the task is assigned. (For distance students, the assignment date will be
Sunday of the week the assignment is posted.) Late assignments will be accepted
for one week with a late penalty of 20%.  Any work received more than one week
after the due date will receive at most 50% of the possible grade.  Scheduling
of computer time outside of regular lab time is the student’s responsibility.
Availability of computers is NOT an excuse for being late with any assignment.
The last date to submit assignments for consideration this semester is May 11,
2017.
