Office Hours
============

..	cssclass::	table-bordered
..	cssclass::	table-striped
..  csv-table::
    :header:    "Day", "Time", "Room"
    :widths:    20,30,30

    TTh, 5:00pm-6:00pm, RGC 3251 or open lab

I reserve these times for distance students. You can call me in my office at
512-223-3199 or visit in person. If you plan on stopping by during this period,
please let me know by email, as I might be at RGC instead of HLC. Contact
me by email to arrange meetings at other times. I can meet you at either RGC or
HLC this term.
