Course Schedule
===============

..  note::

    * Lecture material (and readings) should be reviewed beginning on Monday of the week assigned
    
    * Labs are due on Sunday of the week assigned. **Penalties will be assessed for late submissions**.

    * Exams are available in the testing centers Monday of the week 
      assigned and must be completed by Sunday of that week.

..  cssclass::  table-bordered
..  cssclass::  table-striped

+------+-----------------+--------------------------------------------+-----------+----------------+
| Week | Dates           | Lecture                                    | Lab       | Reading (Text) |   
+======+=================+============================================+===========+================+
| 1    | Sep 26 - Oct 2  | - Course Introduction                      | Lab setup |                |
|      |                 | - Appendix A,B,C,D                         |           | - App A-D      |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 2    | Oct 3 - Oct 9   | - Intro to Computers and Programming       | - Lab 1   | - Ch 1         |
|      |                 | - Texas Four Step                          | - HW 1    |                |
|      |                 | - Programming Languages                    |           |                |
|      |                 | - Input-Process-Output                     |           | - Ch 2         |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 3    | Oct 10 - Oct 16 | - Modules                                  | Scratch   | - Ch 3         |
|      |                 | - Decisions, Structures, & Logic           | Lab 2     | - Ch 4         |
|      |                 | - **Exam 1**                               | Exam1lab  | - Ch 1-4       |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 4    | Oct 17 - Oct 23 | - Repetition Structures                    | Lab 3     | - Ch 5         |
|      |                 | - Functions                                |           | - Ch 6         |
|      |                 | - Input Validaiton                         |           | - Ch 7         |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 5    | Oct 24 - Oct 30 | - C++ Data and Expressions                 | Lab 4     | - Ch 1a, Ch 2a |
|      |                 | - Arrays                                   |           | - Ch 8         |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 6    | Oct 31 - Nov 6  | - Sorting and Searching                    | Lab 5     | - Ch 9         |
|      |                 | - Exam 2 Review                            |           | - Ch 1-10      |
|      |                 | - **Exam 2**                               | Exam2lab  |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 7    | Nov 7 - Nov 13  | - Files                                    |           | - Ch 10        |
|      |                 | - **Exam 2**                               | Exam2lab  |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 8    | Nov 14 - Nov 20 | - Tool Review                              | Lab 6     | - Ch 5a        |
|      |                 | - Function Intro                           |           | - Ch 6a        |
|      |                 | - Graphics Setup                           | Lab 7     |                |
|      |                 | - Simple Graphics                          |           |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 9    | Nov 21 - Nov 27 | - Baby Steps                               |           | - Ch 7a        |
|      |                 | - **Exam 3**                               | Exam3lab  | - Ch 1a-7a     |
|      |                 | - (**Nov 26-27: Thanksgiving**             |           |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 10   | Nov 28 - Dec 4  | - Array Problems                           | Lab 9     | - Ch 8a        |
|      |                 | - C++ Functions                            |           | - Ch 9a        |
|      |                 | - Name Scope Rules                         |           |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 11   | Dec 5 - Dec 11  | - Advanced file operations                 | Lab 10    | - Ch 12a       |
|      |                 | - Files and Strings                        |           |                |
|      |                 | - Strings                                  | Lab 11    |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
| 12   | Dec 12 - Dec 18 | - Object Oriented Programming              |           |                |
|      |                 | - Review for Exam 4                        |           |                |
|      |                 | - **Exam 4**                               |           |                |
+------+-----------------+--------------------------------------------+-----------+----------------+
