Students with Disabilities:
===========================

Each ACC campus offers support services for students with documented physical
or psychological disabilities. Students with disabilities must request
reasonable accommodations through the Office for Students with Disabilities on
the campus where they expect to take the majority of their classes. Students
are encouraged to make this request three weeks before the start of the
semester. (Refer to the Current ACC Student Handbook) "Communications"

Please let me know as soon as you can (before the need arises) that you need
accommodation. I will work with you to make sure you can get this course done
as effectively as possible.
