Grading Policy:
===============

Grade will be based both on concepts and practical application. Exams, quizzes
and homework assignments may be a part of the grade. An overall grade will be
assigned based on the following grading scale:

..  csv-table::
    :header: "Percentage", "Letter Grade"
    :widths: 15, 20

    "90%-100%","A"
    "80%-89%","B"
    "70%-79%","C"
    "60%-69%","D"
    "0%-59%","F"
