Incomplete Grade:
=================

A student may receive a temporary grade of **I** (Incomplete) at the end of
the semester only if ALL of the following conditions are satisfied:

   1. The student is unable to complete the course during the semester due to
      circumstances beyond their control.

   2. The student must have earned at least half of the grade points needed
      for a **C** by the end of the semester.

   3. The request for the grade must be made in person at the instructor's
      office and necessary documents completed.

   4. To remove an **I**, the student must complete the course by two weeks
      before the end of the following semester. Failure to do so will result
      in the grade automatically reverting to an **F**.

