Prohibited Acts :
=================

Acts prohibited by the college for which discipline may be administered
include scholastic dishonesty, including but not limited to cheating on an
exam or quiz, plagiarizing, and unauthorized collaboration with another in
preparing outside work. Academic work submitted by students shall be the
result of their own thought, research or self-expression. Academic work is
defined as, but not limited to tests, quizzes, whether taken electronically or
on paper; projects, either individual or group; classroom presentations, and
homework.
