Safety Statement
================

Each student is expected to learn and comply with ACC environmental, health and
safety procedures and agree to follow ACC safety policies.  Emergency posters
and Campus Safety Plans are posted in each classroom.  Additional information
about safety procedures and how to sign up to be notified in case of an
emergency can be found at `Emergency Notifications
<http://www.austincc.edu/emergency/>`_.

Anyone who thoughtlessly or intentionally jeopardizes the health or safety of
another individual will be immediately dismissed from the day’s activity, may
be withdrawn from the class, and / or barred from attending future activities.


