Testing Policies:
=================

All courses will require that you take tests to verify that you have learned
the material being presented. In my classes, these tests will be in one of
these forms:

    * In class, multiple choice: you are required to bring a green ScanTron
      form to class to record your answers.

    * In class, short answer: I will provide a printed test with space for you
      to write your answer. You are not allowed to use any other paper for your
      answers.

    * Distance, any kind: Distance students are required to take tests in an
      approved ACC Testing center. (See http://www.austincc.edu/campus-contacts
      to find the currently approved center locations.) The test will be taken
      using the Respondus system. You will log into a "lock-down browser" and
      view the test in that browser. You will enter your answers in either text
      boxes, or check boxes in the test pages. Note that it is difficult to
      enter examples of program code in this system, but this is the only
      school-approved system we have for distance classes.

Unless specifically told otherwise, all tests are closed-book tests. I do allow
using any reference materials for lab assignments associated with a test, but
there will be a time limit to complete the work. 
    
