Withdrawal Policy:
==================

Regular and punctual class and laboratory attendance is expected of all
students.  If attendance or compliance with other course policies is
unsatisfactory, the instructor may withdraw students from the class.  

It is the student's responsibility to complete a Withdrawal Form in the
Admissions Office if they wish to withdraw from this class. The last date to
withdraw for this semester is Nov 19, 2015. It is not the responsibility of the
instructor to withdraw the students from their class even though the instructor
has the prerogative to do so under the above listed circumstances.

..  note

    ALERT: Students who enroll for the third or subsequent time in a course
    taken since Fall 2002 are charged a higher tuition rate.  State law permits
    students to withdraw from no more than six courses during their entire
    undergraduate career at Texas public colleges or universities.  With
    certain exceptions, all course withdrawals automatically count towards this
    limit.  Details regard this policy can be found in the ACC College Catalog.
