Learning Outcomes/Course Objectives:
====================================

1.  Recognize basic computer hardware architecture constructs such as
    instructions sets, memory, CPU, external devices, and data representation.

2.  Use programming software tools including compilers, linkers, editors, and
    integrated development environments to create and test programs.

3.  Demonstrate problem solving skills by developing algorithms to solve
    problems incorporating the concept of variables and constants of basic data
    types in a computer program.

4.  Utilize programming constructs which uses input and output devices for
    acquiring and displaying data including sequential files.

5.  Create programming designs which includes step-by-step algorithms and desk
    checking to validate problem solutions.

6.  Incorporate the use of sequential, selection and repetition control
    structures into the algorithms implemented as computer programs.

7.  Demonstrate an understanding of structured design by implementing programs
    with functions and passing of parameters to solve more complex problems and to
    promote the concept of efficient use of code.

8.  Design and implement programs using arrays.


    
