Course Rationale:
=================

This is an entry level programming course designed to teach students the basic
concepts of computer programming.  The course will include designing, coding,
debugging, testing, and documenting programs using a high level programming
language.  This course is intended to be the primary programming course for
students whose academic goals require exposure to programming fundamentals.
