Degree Plans
============

The course is included in several degree plans and certificate, including, in
the Computer Information Systems department, the following:

    * Associate of Applied Science – Information Technology - Applications 

    * Associate of Applied Science – Local Area Network Systems - Local Area Network 
      Administration
      
    * Associate of Applied Science – Local Area Network Systems - Security Administration

    * Associate of Applied Science – Information Technology - User and Computer Support

    * Certificate – Information Technology - User and Computer Support

    * Certificate – Local Area Network Systems - Local Area Network Administration
    
