Scans Competencies:
===================

Maintained in Computer Studies office (RGC1-113)

    * Resources
        * 1.1 Manages time
    * Information
        * 3.1 Acquires and evaluates information
        * 3.2 Organizes and maintains information
        * 3.3 Uses computers to process information
    * Systems
        * 4.1 Understands systems
        * 4.2 Monitors and corrects performance
        * 4.3 Improves and designs systems
    * Technology
        * 5.1 Selects technology
        * 5.2 Applies technology to task
        * 5.3 Maintains and troubleshoots technology
    * Basic Skills
        * 6.1 Reading
        * 6.2 Writing
        * 6.3 Arithmetic
        * 6.4 Mathematics
        * 6.5 Listening
    * Thinking Skills
        * 7.1 Creative thinking
        * 7.2 Decision making
        * 7.3 Problem solving
        * 7.4 Mental visualization
        * 7.5 Knowing how to learn
        * 7.6 Reasoning
    * Personal Skills
        * 8.1 Responsibility
        * 8.2 Self-esteem
        * 8.3 Sociability
        * 8.4 Self-management
        * 8.5 Integrity/honesty

